/home/live/store/wg/site/log/out.log {
    size 10M
    rotate 16
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    olddir /home/live/store/wg/site/log/old
    postrotate
        systemctl restart site.service > /dev/null 2>&1 || true
    endscript
}
