name: Deploy site to production environment (live)

# start action manually
on: workflow_dispatch

env:
  PATH_TARGET: /home/live/inst/wg/site
  PRJ: site_wg
  ZIP: site_wg.zip

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repo.
        uses: actions/checkout@v3

#      - name: Build application.
#        run: |
#          ./bin/deploy/live.sh

      - name: Add application files to archive.
        uses: montudor/action-zip@v1
        with:
          args: zip -qq --exclude=*.git* -r ${{env.ZIP}} ./

      - name: Validate archive existence.
        run: ls -lh ${{env.ZIP}}

      - name: Copy files to Remote Server.
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_CONTABO }}
          REMOTE_USER: ${{ secrets.REMOTE_USER_CONTABO }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY_CONTABO }}
          ARGS: "-rltgoDzvO"
          SOURCE: "${{env.ZIP}}"
          TARGET: "${{env.PATH_TARGET}}.new/"
